name: Build PyZMQ for Termux (ARM64)

on:
  workflow_dispatch:

jobs:
  build-pyzmq-arm64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PyZMQ Source
      uses: actions/checkout@v4
      with:
        repository: zeromq/pyzmq
        ref: v26.4.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull Cross-Compiler
      run: docker pull dockcross/manylinux2014-aarch64

    - name: Generate dockcross script
      run: docker run --rm dockcross/manylinux2014-aarch64 > ./dockcross-aarch64.sh

    - name: Make script executable
      run: chmod +x ./dockcross-aarch64.sh

    - name: Build wheel using dockcross
      run: |
        ./dockcross-aarch64.sh bash -c "\
          yum update -y \
          && yum install -y epel-release \
          && yum install -y gcc gcc-c++ make \
             python3 python3-devel python3-setuptools python3-wheel \
             zeromq zeromq-devel \
             which \
          && python3 -m ensurepip \
          && python3 -m pip install --upgrade pip \
          && pip3 install build cython \
          && cd /work && python3 -m build --wheel \
          && mkdir -p /output && cp dist/*.whl /output/"

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pyzmq-arm64-wheel
        path: ./dist/*.whl
